### ISSUE TITLE
"Could not access excludesFile" in multi-level project

### ISSUE THREAD

**Issue by ZexinLee** [gliga/ekstazi#13]
If including ekstazi as a maven plugin in pom.xml, it requires <excludesFile> parameter for maven-surefire-plugin. Although ekstazi will create a default excludes list file for the pom.xml, it seems that it ignores all sub-packages and may cause "Could not access excludesFile" in later maven running process.

**Comment by ZexinLee** [comment]
Take https://github.com/apache/httpcomponents-client as an example, I tried to integrate this maven project with Ekstazi, however, I met this problem and had to make the copies the excludes list file to every subpackage path to fixing this problem.

The project structure is like this:
--httpcompoments-client:
----httpclient5
----httpclient5-cache
----httpclient5-fluent
----httpclient5-testing
----httpclient5-win
When running Ekstazi, it only create exclude list file on "httpcompoments-client" level, I had to copy this file to every sub-package to avoid runtime error.

**Comment by gliga** [comment]
Hi,

Thanks for your interest in Ekstazi.  Which version of the tool do you use?  Ekstazi does not use excludesFile any longer.  The latest version is 5.4.0.

If you still have some problems, please send me an example repo in which you integrated Ekstazi.

Hope it works for you, but let me know if you  have other questions.

**Comment by ZexinLee** [comment]
Thanks for your reply.
I used version 5.3.0 as guidance in http://www.ekstazi.org/index.html and the latest revision on master branch. Is version 5.4.0 remove excludesFile?

**Comment by gliga** [comment]
I think you are looking at some very old version.  excludesFile was removed 4-5 years ago (before 5.x release).  If you are using Maven, you only need the following (from the ekstazi.org page):

 <plugin>
        <groupId>org.ekstazi</groupId>
        <artifactId>ekstazi-maven-plugin</artifactId>
        <version>5.3.0</version> 
        <executions>
          <execution>
            <id>ekstazi</id>
            <goals>
              <goal>select</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

**Comment by ZexinLee** [comment]
got it!
