### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by msridhar** [gliga/ekstazi#2]
It would be great if Ekstazi could be used with Gradle, in addition to the extant Maven and Ant support.  Or perhaps the existing support is sufficient to use Ekstazi with Gradle?  If so, some documentation on how to do so would be appreciated.  Thanks!

**Comment by todaytomorrow** [comment]
Dear Manu,

Thanks for the question.  We have been planning to support Gradle for several months, but have not received any official request until your message.  We plan to look at this soon and update the issue.  Let us know if you need the Gradle support more urgently and if you need it for a specific project that is publicly available (so we can use it for testing).

**Comment by msridhar** [comment]
There is the [MemInsight](https://github.com/Samsung/meminsight) project, but getting the Java tests to pass for the first time also requires installation of node.js and a couple other tools, so it's a bit painful.  (If you're interested in going through the steps, let me know and I'll give directions.)  If/when you have a snapshot build with candidate support, I'm happy to grab it and test it out for you; just let me know.

**Comment by kageiit** [comment]
Gradle support is available in https://github.com/kageiit/ekstazi-gradle-plugin

**Comment by gliga** [comment]
Thanks Gautam for the contribution.
