### ISSUE TITLE
ekstazi-maven-plugin select goal fails when ${basedir} contains spaces

### ISSUE THREAD

**Issue by n340930** [gliga/ekstazi#3]
Hi!

I'm trying to run the Maven plugin from a folder located under "c:\users\user123\myproj". It seems this path is resolved "to c:\documents and settings\user123\myproj" which causes the goal to fail, most likely because of the spaces. If I override <parentdir> to the former one everything works fine, but it will obviously not be very portable...

Would be great if this issue could be fixed, this plugin looks very nice!

/ Daniel

**Comment by todaytomorrow** [comment]
Dear Daniel,

Thanks for the report.  Could you send us (or upload on GitHub) a small example that we can use to reproduce the problem that you described.  We would be happy to look at the problem and update the plugin.

Milos

**Comment by n340930** [comment]
I can't upload the actual project I'm working on, but I just followed the "1. Maven Central" instruction at http://www.ekstazi.org/maven.html.

**Comment by todaytomorrow** [comment]
No worries, we do not need the actual project.  However, it would be very helpful if you can make a small example (independent of your project) that illustrates the problem.  The example can be as simple as the HelloWorld, which uses Maven to build the project and includes Ekstazi plugin; the directory structure of the example should be s.t. the error in the plugin can be observed.

**Comment by n340930** [comment]
Absolutely! I've created a simple project, do you have an email address I can send it to?

**Comment by n340930** [comment]
Basically the problem seems to be that the maven plugin fails if your project folder path contains space characters.

**Comment by todaytomorrow** [comment]
There are multiple options.  Ideally, you can upload the simple project to github and give us the access permission (if you decide to keep it private).  Another option (if really has to be that way) is to send us the project via email (which are available on our web page(s)).

**Comment by n340930** [comment]
You got mail... :)

**Comment by gliga** [comment]
Fixed in 4.6.1
