### ISSUE TITLE
Support for SBT for scala projects

### ISSUE THREAD

**Issue by ayush9999-qa** [gliga/ekstazi#36]
Do we have support of ekstazi for scala projects using sbt? I tried adding following sbt dependencies to scala project, ran scalatests for first time and then ran scala tests with changes but seems like all the tests ran on second run as well.

https://mvnrepository.com/artifact/org.ekstazi/org.ekstazi.core/5.3.0
https://mvnrepository.com/artifact/org.ekstazi/org.ekstazi.scalatest/5.3.0

Can someone please tell me if ekstazi supports sbt projects and what is the correct way to run ekstazi?

**Comment by gliga** [comment]
Hi, Ekstazi does not support sbt projects.  Prior support for Scala was through Maven.

**Comment by gliga** [comment]
Closing as we have no plans to support Scala projects any further.
