### ISSUE TITLE
Error opening zip file or JAR manifest missing

### ISSUE THREAD

**Issue by pawan-sant** [gliga/ekstazi#38]
Hi,

Getting below error when trying to run with Ant. Works well with Maven.

ekstazi:select] Ekstazi Ant: version = 4.6.1
[ekstazi:select] Ekstazi Ant: jar = file:/C:/Users/wouter/R_20.1.0/lib/org.ekstazi.core-4.6.1.jar
[junit] Error occurred during initialization of VM
[junit] agent library failed to init: instrument
[junit] Error opening zip file or JAR manifest missing : /C:/Users/wouter/R_20.1.0/lib/org.ekstazi.core-4.6.1.jar
[junit] Running MyTest
[junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec

Tried with other versions on core jar as well but getting same error. Also checked that jar exists and isReadble.

Any help will be appreciated.

Thanks

**Comment by gliga** [comment]
The latest version of Ekstazi is 5.3.0.  You might want to try it.  

If you observe the same on Linux, I can take a look; otherwise I have no way to debug this.

**Comment by pawan-sant** [comment]
Hi, we did try with latest 5.3.0 and got same error. Tried some other versions as well. 

Dont have linux setup so could not test on it. Any other things we can try on Windows?

**Comment by gliga** [comment]
If you have a very simple case that is failing, I can test it on Linux.  If I observe the same output, I can debug.

**Comment by gliga** [comment]
Closing as we have no plans to support Ant build system any longer.
(And Ekstazi version was not matching the latest at the time of earlier comments.)
