### ISSUE TITLE
Source file to test file mappings

### ISSUE THREAD

**Issue by ehsan-salamati** [gliga/ekstazi#42]
Hi,
I wonder if there is a way that I can get access to the graph (source file to test file mappings) that gets built by ekstazi after a certain run.

**Comment by gliga** [comment]
Yes, all the mappings should be available in `.ekstazi` directory (from which you were running Ekstazi/build).

**Comment by ehsan-salamati** [comment]
Thanks for your reply. What I see in the `.ekstazi` directory is some files named similar to the tests that exist in my project. However, inside each is just some hashed numbers. I was wondering if I could understand for each test file what were the source files that could trigger the test file run.

**Comment by ehsan-salamati** [comment]
Thank you @gliga 🙏 
One last question, does ekstazi also support kotlin? I was wondering if I can use it for an android project.

**Comment by gliga** [comment]
In theory any project/code that compiles to Java bytecode is supported (we used Ekstazi with Scala projects in the past).

There was a group of students that was trying to enable Ekstazi for Kotlin, but I do not know the status of that (or if that code is publicly available).
