### ISSUE TITLE
Ekstazi ant task jar doesn't load on Windows

### ISSUE THREAD

**Issue by wvreeven** [gliga/ekstazi#6]
When Ekstazi is called from Ant on a Windows environment, the path to the Ekstazi core jar is constructed incorrectly and the JUnit tests are marked as failed:

[ekstazi:select] Ekstazi Ant: version = 4.6.1
[ekstazi:select] Ekstazi Ant: jar =  file:/C:/Users/wouter/R_20.1.0/lib/org.ekstazi.core-4.6.1.jar
    [junit] Error occurred during initialization of VM
    [junit] agent library failed to init: instrument
    [junit] Error opening zip file or JAR manifest missing : /C:/Users/wouter/R_20.1.0/lib/org.ekstazi.core-4.6.1.jar
    [junit] Running MyTest
    [junit] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec

This happens also when the path to the jar in the build.xml file is defined as

C:\Users\wouter\R_20.1.0\lib\org.ekstazi.core-4.6.1.jar

Please confirm and fix this issue. Many thanks in advance!

**Comment by gliga** [comment]
Hi,

Thanks for the report.  Do you still have the same problem on Windows (with the latest version of Ekstazi)?  If yes, could you provide a simple example that illustrates the case.  I would be happy to update this case.

**Comment by wvreeven** [comment]
Hi, thanks for the belated reply. This doesn't seem to be an issue anymore. Please close this issue.

**Comment by gliga** [comment]
Thanks for the confirmation.

**Comment by pawan-sant** [comment]
I am still facing this same issue with latest version of core jar. Any help?

**Comment by pawan-sant** [comment]
@wvreeven  - Could you please help me. Stuck on this same error from some time.

**Comment by wvreeven** [comment]
I am sorry but I cannot help you since I no longer am on any project using ekstazi.

**Comment by pawan-sant** [comment]
Thanks @wvreeven no worries!

@gliga - Can you help please.

**Comment by gliga** [comment]
Hi, do you know if this happens on Linux as well?  I have no access to any Windows machine, so I cannot debug if this is a Windows specific issue.

**Comment by gliga** [comment]
By the way the latest Ekstazi version is 5.3.0 in case you are using anything order than that you should try updating.

**Comment by pawan-sant** [comment]
Hi Gilga, no we didnt test in Linux. We did test with latest and some other versions and still got the same error.
