### ISSUE TITLE
Ekstazi and Java 9

### ISSUE THREAD

**Issue by wvreeven** [gliga/ekstazi#7]
Using Ekstazi with Java 9 resolves in an illegal access warning:

    [junit] WARNING: An illegal reflective access operation has occurred
    [junit] WARNING: Illegal reflective access by org.ekstazi.monitor.CoverageMonitor (org.ekstazi.core-4.6.0.jar) to constructor java.io.File(java.lang.String,int)
    [junit] WARNING: Please consider reporting this to the maintainers of org.ekstazi.monitor.CoverageMonitor
    [junit] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    [junit] WARNING: All illegal access operations will be denied in a future release

Please fix this :)

**Comment by gliga** [comment]
Please try Ekstazi 5.0.1.  This is the first version that supports Java 9.  (If you decide to  use Maven you will need to pass -Djvm.options=jdk.attach.allowAttachSelf=true .)

**Comment by wvreeven** [comment]
Thanks, problem solved.
