### ISSUE TITLE
NullPointerException when running ekstazi:ekstazi goal

### ISSUE THREAD

**Issue by frollo** [gliga/ekstazi#8]
I'm trying to run Ekstazi on newly created maven project, but the `ekstazi:ekstazi` goal always fails with a NullPointerException.

## Steps to reproduce

Generate a new project with

        mvn -B archetype:generate \
         -DarchetypeGroupId=org.apache.maven.archetypes \
         -DgroupId=com.mycompany.app \
         -DartifactId=my-app

Then add the Surefire and Ekstazi plugins as in the [guide](http://www.ekstazi.org/maven.html) and run

    mvn ekstazi:ekstazi

## Debugging log
I've run `mvn ekstazi:ekstazi -X` to get the debugging log and stored it [here](https://github.com/gliga/ekstazi/files/1606377/ekstazi_err.log)

**Comment by gliga** [comment]
Hi,

Thanks for the report.  Unfortunately, I am not able to reproduce by following the outlined steps (although I can in code where the bug might happen). Do you mind attaching pom.xml or ideally the entire small project that you have; if that still works on my machine, I could check your version of Maven and Java.

**Comment by frollo** [comment]
I've zipped the whole project, [here](https://github.com/gliga/ekstazi/files/1607287/pizza.zip) it is

**Comment by gliga** [comment]
You can check 5.2.0. Let me know if you are still facing the problem. (Sorry for the late reply; nobody is actively looking at the code these days).
